### PR TITLE
Modernize Zope Committer Agreement

### PR DESCRIPTION
**Pull request by tseaver**
- Document building the docs using pip + Sphinx. 
- Include source as OpenOffice document.
- Remove fax number.
- Add a line for Github committer ID.

Closes https://github.com/zopefoundation/www.zope.org/issues/5.

### CODE REVIEW

**Comment by jugmac00** [comment]
Hi Tres, there was a minor formatting issue within the document (bullet/enumeration 7 d) and 7 di). See pull request #4.

**Comment by tseaver** [comment]
@jugmac00 Thanks!  I tweaked it once more to get rid of the extra whitespace after the `d)`.

**Review by icemac — APPROVED** [review]
LGTM.

**Comment by icemac** [comment]
@tseaver What needs to be done so the new ZCA gets online at http://docs.zope.org/developer/becoming-a-committer.html?

**Pull request merged**
